NerdWalletOSS/shepherd

src/adapters/base.ts
src/adapters/git.ts
src/adapters/github.test.ts
src/adapters/github.ts
src/commands/checkout.ts

I couldn't do this directly in `getCandidateRepos`, as that isn't called when `--repos` are specified. I opted to add a new adapter method that can do this work for all checked-out repos after they've been checked out.
I'm beginning to think that `BaseAdapter` should actually be an abstract class instead of an interface - this new function should probably be a no-op by default.

Save default branch at checkout

---

.npmrc
package-lock.json
package.json
src/util/generate-pr-message.ts

This regenerates our `package-lock.json` to use the public npm registry instead of Artifactory. Also adds an `.npmrc` that sets the registry to the public one to work around global overrides for NW employees.

Use the public npm registry

---

.travis.yml
package.json

This will automatically release Shepherd on npm when a new tag is pushed to the repo. This is untested but will only run on master, so it might take a bit of trial and error to get things working correctly.

Add automatic npm deployment

---

.travis.yml

This prevents `node_modules` from being deleted before we try to run tests and publish.

Skip cleanup during travis npm publish

---

package.json

By default, scoped packages are published as private. This makes our package public.

Update publish config to make the package public

---

CHANGELOG.md
README.md
src/adapters/git.ts

Git repo history is not needed, this should make cloning faster.

Use shallow git clones

---

package-lock.json
package.json
src/adapters/github.test.ts
src/adapters/github.ts

Updating Jest to the latest to resolve the [security alerts](https://github.com/NerdWalletOSS/shepherd/network/alerts) from 
* deep-extend
* merge
* handlebars

fix: upgrade deps to non-vuln versions

---

CHANGELOG.md
src/util/execute-steps.ts

I'm not sure why this file imports from `../../node_modules/<dependency>` but it's currently breaking my CLI usage when installing with yarn
**EDIT**: I assumed this was `yarn` but it also happens with `npm`

Remove ../ from a node_modules import

---

CHANGELOG.md
src/adapters/github.ts

Fixes #77
It's also a partial fix for #61 I think
I'm like 90% sure this is a good change because you'd need Github creds to be able to push a branch for a PR, but I don't know all the use-cases for this tool yet so 🤷‍♂I could be wrong!

Throw a more useful error if no github credentials are found

---

CHANGELOG.md
README.md
src/adapters/base.ts
src/adapters/git.ts
src/adapters/github.ts
src/util/exec-in-repo.ts

Occasionally repositories are set up with their default branch as not master, and some migrations may need that information. E.g. I was working on a migration to add main-branch-only build notifications, and had no way to figure out what that branch was.

Add SHEPHERD_BASE_BRANCH

---

CHANGELOG.md
README.md
src/adapters/base.ts
src/adapters/git.ts
src/adapters/github.ts
src/util/exec-in-repo.ts
src/util/execute-steps.ts

I'd like my GitHub PR messages to include permalinks, so they are rendered like this:
https://github.com/NerdWalletOSS/shepherd/blob/8048f846335ab5b16c6931b01c8974d2a8914406/package.json#L2-L8
In order to do this my PR script needs to be able to generate URLs that look like:
```
https://github.com/NerdWalletOSS/shepherd/blob/8048f846335ab5b16c6931b01c8974d2a8914406/package.json#L2-L8
```
This requires the message generator to have access to the owner, repo, and revision being operated on. As far as I can tell that isn't currently possible. 
It looks like there is a precedent for some of this information as environment variables at script time, including the `branch` of the current repo:
https://github.com/NerdWalletOSS/shepherd/blob/8048f846335ab5b16c6931b01c8974d2a8914406/src/util/exec-in …

Enable adapters to add environment variables

---

.dependabot/config.yml

- add dependabot config file.
- adds 'chore' prefix to dependabot's commit messages so that corresponding semantic-release is triggered.

feat: add dependabot config file.

---

.dependabot/config.yml

This PR adds auto-merge for all production and development security and semver **patch** updates.
For production dependencies, commits messages will be prefixed with`fix` resulting in CI/CD tagging and publishing a new patch version to npm.
For development dependencies, commit messages will be prefixed with `chore` and will not result a new tag or a new patch version being published to npm.

chore: update dependabot config.

---

src/adapters/github.ts

This change improves the experience of using the CLI by making repo names case insensitive. That is, the following two commands will work exactly the same:
```
shepherd pr --repos nerdwallet/foobar
shepherd pr --repos NerdWallet/FooBar
```
cc @taylor-chen

fix: use case-insensitive compare for repo names

---

renovate.json

Also, don't auto update major types (to match installed package version)

chore: auto update dev dependencies

---

package-lock.json
package.json
src/adapters/git.ts

Recent versions of `simple-git` deprecated the `.silent()` API, which now spams the console with a deprecation notice whenever it's used:
```
simple-git deprecation notice: git.silent: logging should be configured using the `debug` library / `DEBUG` environment variable, this will be an error in version 3
```
This PR drops the use of that API. The logger is now silent by default, which is the behavior we want.

fix: drop deprecated silent() from simple-git

---

README.md
docs/tutorial.md

So the shell doesn't try to run the backtick-wrapped parts as commands.
To fix this essentially:
```
> echo "Hey! This PR renames `.eslintrc` to `.eslintrc.json`"
.eslintrc: command not found
.eslintrc.json: command not found
Hey! This PR renames  to
```
---
Also this is my first time using conventional-commits. Let me know if I messed anything up, or if I could do things better.

docs: Change the pr_message examples to use single-quotes

---

package.json
yarn.lock

`yarn.lock` already had `@octokit/rest` at the latest version, but I want to ensure that Shepherd consumers get that version too - apparently that's important for our Octokit plugins to work correctly.

chore: Bump @octokit/rest to latest version

---

.github/workflows/release.yml

Our few most recent commits to master have failed to publish because `semantic-release` couldn't push new versions to `master`. Per https://github.com/semantic-release/semantic-release/blob/8fda7fd423d24e7b425fbee83790f49dd0478e2d/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch, we should be setting `persist-credentials: false` during checkout so that our custom token (that can bypass branch protection restrictions) is used by `semantic-release`.

fix: Use custom GitHub token to bypass branch protection

---

.eslintignore
CHANGELOG.md

Eslint is enabled on CHANGELOG.md file.  There has been a recent change wherein either the linter or semantic-release changes result in a linting error.  In particular, items now leverage a `-` instead of `*` where linter rules are enforcing the use of the former, not the latter.
This change simply disables linting on this file.

fix(lint): ignore linting on CHANGELOG.md file

---

.prettierignore

Disabling prettier on CHANGELOG.md as this is unnecessary and breaks our CI.  If we feel strongly that we want to run prettier on this file, can always revisit.

fix(prettier): ignore CHANGELOG.md file when running prettier

---

package-lock.json
src/adapters/base.ts
src/adapters/git.ts
src/adapters/github.test.ts
src/adapters/github.ts
src/cli.ts
src/commands/checkout.ts
src/commands/pr.ts
src/migration-context.ts
yarn.lock

* Adds support for contributions via fork model.  For more details, see: https://github.com/NerdWalletOSS/shepherd/pull/629

feat: added options to create pr from fork to upstream

---

.releaserc.js

The semantic-release configuration (i.e., `.releaserc.js`) can be simplified by leveraging existing presets.  Towards that end, we will leverage `conventionalcommits` preset going forwrard.  The preset is extendible, so adjustments can be made as needed.

chore(config): update semantic releasee config

---

README.md
package-lock.json
package.json
yarn.lock

When using non-default preset for commit-analyzer, we need to also install the module.  We now use conventionalcommits preset and this PR installs the corresponding dependency.

fix(semantic-release,docs): add commit-analyzer conventionalcommmits preset module

---

package-lock.json
package.json
src/adapters/adapter.mock.ts
src/commands/checkout.test.ts
src/commands/checkout.ts
src/logger/logger.mock.ts
src/logger/spinner.mock.ts

* Work towards increasing test coverage on commands.

chore(testing): add unit tests for checkout

---

README.md
src/adapters/github.test.ts
src/adapters/github.ts

Shepherd currently uses ssh git urls to clone repositories.
This assumes that ssh auth is available in the environment for all repositories being cloned.
We are trying to use GitHub Actions to run Shepherd, with a GitHub App providing authentication.
This works for the API (we can have the GitHub App's API token get used by shepherd), but GitHub Apps do not have SSH keys associated with them to allow git pushes over ssh.
They can however use http authentication with their GitHub token to perform git pushes, which this PR allows for using (`SHEPHERD_GITHUB_ENTERPRISE_BASE_URL=x-access-token:${GITHUB_PAT}@github.com`)

feat: Add https auth

---

README.md
package-lock.json
src/adapters/github.test.ts
src/adapters/github.ts

This pull request includes changes to the `README.md` and `src/adapters/github.ts` files to improve the handling of GitHub Enterprise URLs and repository URLs, as well as updates to the test cases in `src/adapters/github.test.ts` to cover these changes.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L29-R29): Corrected the example value for `SHEPHERD_GITHUB_ENTERPRISE_BASE_URL` to `github.com` instead of `api.github.com`.
* [`src/adapters/github.ts`](diffhunk://#diff-275c76f8995ad367ffe7a0c7f165d04a769a1e094ccf05a3b053ee1f71e2aa5bL11-L14): Refactored the `getRepositoryUrl` method to handle different protocols (`ssh` and `https`) and provide a default value for `SHEPHERD_GITHUB_ENTERPRISE_BASE_URL`. Removed redundant environment variable …

feat(auth): add support for https protocol (#748)

---

e2e/__snapshots__/cli.test.ts.snap
e2e/cli.test.ts
examples/eslintrc-yml/shepherd.yml
package-lock.json
src/commands/apply.test.ts
src/commands/apply.ts
src/commands/checkout.test.ts
src/commands/checkout.ts
src/commands/pr-status.test.ts
src/commands/pr-status.ts
src/commands/pr.test.ts
src/commands/pr.ts
src/logger/logger.mock.ts
src/util/__snapshots__/execute-steps.test.ts.snap
src/util/exec-in-repo.test.ts
src/util/exec-in-repo.ts
src/util/execute-steps.test.ts
src/util/execute-steps.ts
src/util/for-each-repo.ts

This pull request focuses on enhancing the end-to-end (e2e) tests for the CLI, improving the migration process, and refactoring the code for better readability and maintainability. The most important changes include adding new test cases, modifying existing snapshots, and refactoring the `apply` command to improve error handling and logging.
* Added a new `afterAll` hook to clean up test migration directories after tests run in `e2e/cli.test.ts`.
* Updated test cases to handle migrations targeting single and multiple repositories, and modified snapshots accordingly in `e2e/cli.test.ts` and `e2e/__snapshots__/cli.test.ts.snap`. [[1]](diffhunk://#diff-8f658759cecae7097a5385da68e4f55fbde7218ad6151fcb6dc6563cedf0f712L36-L53) [[2]](diffhunk://#diff-6b30a68f3a2070193e344f627f19aa9569abcd00e3dc67 …

feat(asyn/await): parallelize commands

---

.prettierrc.mjs
e2e/__snapshots__/cli.test.ts.snap
eslint.config.js
jest.config.js
jest.e2e.config.js
package-lock.json
package.json
src/util/migration-spec.ts

* [`src/util/migration-spec.ts`](diffhunk://#diff-6b79e0a66e3ebb223be40ceb5397f1123ce8b0f7853009086f0730a04bdcb793L4-R5): Refactored lodash import to use a single import statement and destructure the required methods.
* Updated e2e snapshots to account for new issues commands
* Cleaned up config files (e.g., jest.config.cjs, ...)

fix(v3): lodash, e2e

---

README.md
package-lock.json
src/adapters/github.test.ts
src/adapters/github.ts

This pull request introduces a new feature to the `GithubAdapter` class that allows the base branch to be determined dynamically based on an environment variable. It also includes corresponding unit tests to ensure the new behavior works as intended.
* [`src/adapters/github.ts`](diffhunk://#diff-275c76f8995ad367ffe7a0c7f165d04a769a1e094ccf05a3b053ee1f71e2aa5bL293-R293): Updated the `getBaseBranch` method to check for the `SHEPHERD_BASE_BRANCH` environment variable. If it is set, the method returns its value; otherwise, it falls back to the repository's default branch (`repo.defaultBranch`).
* `src/adapters/github.test.ts`: Added a new test suite for the `getBaseBranch` method. This includes tests for scenarios where:
- The `SHEPHERD_BASE_BRANCH` environment variable is not set, and the …

fix(env-var): respect SHEPHERD_BASE_BRANCH
