NerdWalletOSS/shepherd

- .travis.yml
- src/adapters/github.test.ts
Turning on Travis for tests :tada:
> Add travis.yml file

- README.md
- src/adapters/base.ts
- src/adapters/git.ts
- src/adapters/github.test.ts
- src/adapters/github.ts
- src/cli.ts
- src/commands/apply.ts
- src/commands/push.ts
- src/commands/reset.ts
- src/util/for-each-repo.ts
Adds some improved safety checks to make sure we don't overwrite human commits, push to closed PRs, and more.
This 100% needs comprehensive documentation, but I'm going to save that for another PR where I'll do a revamp of the docs to make it more palatable to complete newcomers.
> Add advanced safety features for applying and pushing

- README.md
Feel free to reject this and place it in a more natural location.
> Refer back to the blog

- .gitignore
- CHANGELOG.md
- docs/tutorial.md
- package-lock.json
- package.json
- src/adapters/base.ts
- src/adapters/git.ts
- src/adapters/github.ts
- src/commands/checkout.ts
- src/util/octokit.ts
Fix for https://github.com/NerdWalletOSS/shepherd/issues/57
Also should fix https://github.com/NerdWalletOSS/shepherd/issues/56
> adding github rate failure support by abiding by retry-after

- README.md
Illustration credit to @raissap
> Add Shepherd illustration to readme

- src/adapters/github.ts
> Update github.ts to fix typo in error message

- CHANGELOG.md
- src/adapters/github.ts
Just makes it a bit nicer to see success!
> Add magenta highlighting to merged PRs

- package-lock.json
- package.json
A couple of semantic-release packages were missing and relied upon in GitHub workflow.  This PR adds them:
- @semantic-release/changelog
- @semantic-release/git
> fix: missing packages.

- .dependabot/config.yml
> fix: spacing.

- package-lock.json
- package.json
- update commander to v5
- update preferences to v2
> refactor: update dependencies.

- .travis.yml
- package-lock.json
- renovate.json
> chore: drop node 8; add node 14.

- renovate.json
- Add node 14 to supportPolicy.
> fix: supportPolicy.

- renovate.json
- prefer explicit node versions in supportPolicy
> chore: prefer explicit node versions in supportPolicy.

- package-lock.json
- package.json
- src/adapters/git.ts
> chore: update simple-git.

- package-lock.json
- package.json
- src/util/migration-spec.test.ts
- src/util/migration-spec.ts
> chore: update @hapi/joi to joi

- .github/workflows/ci.yml
- Adding GitHub action to handle testing against node 12, 14, and 16.
1. see https://github.com/NerdWalletOSS/shepherd/issues/494
> chore: add GitHub Actions.

- .github/workflows/ci.yml
Add event trigger for ci gh action.
> chore: add event trigger for ci gh action.

- .releaserc.js
Update .releaserc.js to enable publishing to npm.
> chore: update .releaserc.js.

- src/adapters/github.test.ts
- src/adapters/github.ts
- src/services/github.test.ts
- src/services/github.ts
Implements the same feature as https://github.com/NerdWalletOSS/shepherd/pull/323 but for code search!
> feat: Exclude archived repos when using code search

- .github/workflows/release.yml
* Update GH Token name in release workflow.
> fix(token): update token name.

- CHANGELOG.md
- package-lock.json
- yarn.lock
> fix(lockfiles): add lock files.

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
* update actions and semantic-release
> chore(dep,workflows): update actions and semantic-release

- .github/workflows/semantic-pr-check.yml
* Remove Semantic Pull Request App
* Add action-semantic-pull-request
> feat(workflow): use semantic-pr-check in favor of semantic pull request app

- README.md
- docs/releasing.md
- renovate.json
1. Update CI/CD from Travis CI to GitHub Actions in documentation.
> chore(docs): Update CI/CD documentation

- package-lock.json
- package.json
- src/cli.ts
- yarn.lock
1. Upgrade Commander to latest, v11
> chore(dep): update dependencies - Commander

- src/adapters/base.ts
- src/adapters/git.ts
- src/adapters/github.test.ts
- src/adapters/github.ts
- src/cli.ts
- src/commands/pr.ts
- src/migration-context.ts
fix lint error for pr support feature
> fix lint error for pr support feature

- .github/workflows/release.yml
- docs/releasing.md
- fixtures/artifacts/.shepherd/load-repo-from-file/repos.json
- fixtures/artifacts/.shepherd/yaml-to-json/repos-artifact.yml
- src/adapters/github.test.ts
- src/adapters/github.ts
- src/services/github.test.ts
- src/util/persisted-data.test.ts
1. Update code to use inclusive language
> chore(inclusive-language): update code to use inclusive language

- .releaserc.js
1. Updating release branch to main.
> fix(release): update release branch

- .releaserc.js
> fix(ci/cd): sync tag and package version

- src/commands/commit.test.ts
- src/commands/pr-preview.test.ts
* Add unit tests to cover commit command.
* Add unit tests to cover pr-preview command.
> chore(testing): add unit tests for commit

- src/adapters/github.test.ts
- src/commands/apply.test.ts
- src/commands/apply.ts
- src/commands/list.test.ts
- src/commands/pr-preview.test.ts
- src/commands/pr-status.test.ts
- src/commands/pr.test.ts
- src/commands/push.test.ts
- src/commands/reset.test.ts
- src/services/github.test.ts
* Increase test coverage for commands:
* apply
* push
* reset
* Replaced deprecated jest methods:
* toBeCalledWith -> toHaveBeenCalledWith
* toBeCalledTimes -> toHaveBeenCalledTimes
> chore(testing): increase test coverage for commands

- .github/workflows/release.yml
- README.md
- src/util/exec-in-repo.test.ts
- src/util/execute-steps.test.ts
* Add test coverage for:
* utils/exec-in-repo
* utils/execute-steps
TBD
> chore(testing): increase test coverage

- package-lock.json
- src/adapters/git.ts
This pull request includes improvements to the `GitAdapter` class in the `src/adapters/git.ts` file to enhance code readability by removing console log statements and refining error handling.
Code readability improvements:
* [`src/adapters/git.ts`](diffhunk://#diff-eb86ec4ccc1c03766f6b511a687ac25f37fde89cbeb54552f93f2c65c24722c9L34): Removed a console log statement from the `checkoutRepo` method to reduce unnecessary logging.
* [`src/adapters/git.ts`](diffhunk://#diff-eb86ec4ccc1c03766f6b511a687ac25f37fde89cbeb54552f93f2c65c24722c9L48-R52): Refined error handling in the branch creation and switching logic by removing console log statements and adding comments for clarity.
> fix(logging): remove excess logging

- CONTRIBUTING.md
This pull request introduces a comprehensive `CONTRIBUTING.md` file to guide contributors on how to effectively contribute to the Shepherd project. The document includes sections on the code of conduct, how to report bugs, suggest enhancements, contribute code, set up the development environment, run end-to-end tests, follow the style guide, and the pull request process.
Key additions:
* [`CONTRIBUTING.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R1-R101): Added a detailed guide for contributing to the Shepherd project, including sections on code of conduct, reporting bugs, suggesting enhancements, contributing code, development setup, running e2e tests, style guide, and pull request process.
> docs(contributing): Create CONTRIBUTING.md

- jest.config.cjs
- jest.setup.ts
Add jest setup file to ensure consistency in unit tests.
> chore(testing): add jest setup file

- package-lock.json
> chore(deps): refresh package-lock

- README.md
Updated README to reflect project relocation and sunset notice.
> chore(repo-migration): Revise README for project archive and new location
